version: '3'

services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: ideas
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: ''
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
